flavour: std::Matrix Class Reference
std::Matrix Class Reference
#include <multivector.h>
Public Member Functions
Matrix ()
Matrix (const Matrix &m)
Matrix (const char *m[3][3])
constructs a symbolic matrix with the symbols names given by the argument
Matrix (const char *name, const char **index1, const char **index2)
constructs a symbolic matrix with the symbols names given by the arguments
Matrix (ex m1, ex m2, ex m3)
constructs a diagonal matrix
Matrix (ex m1)
constructs a diagonal matrix with all diagonal elements equal
Matrix (ex t12, ex t13, ex t23, ex d13)
constructs a unitary matrix in the standard form
ex cs (ex t12)
used in the unitary constructor
ex sn (ex t12)
used in the unitary constructor
Matrix conjugate () const
computes the hermitian conjugate of the matrix
Public Member Functions inherited from std::multivector< ex, 2 >
multivector ()
Default constructor.
multivector (const multivector &m)
Copy constructor.
multivector (const ex &value,...)
Recommended constructor.
multivector (const ex &value, va_list &listPointer)
Auxiliary constructor (recursive)
Additional Inherited Members
Public Types inherited from std::multivector< ex, 2 >
typedef vector< multivector< ex, N-1 > > v
Detailed Description
Definition at line 67 of file multivector.h.
Constructor & Destructor Documentation
std::Matrix::Matrix () inline
Definition at line 70 of file multivector.h.
 : multivector< ex,2>(0,3,3) {}
std::Matrix::Matrix (const Matrix & m) inline
Definition at line 72 of file multivector.h.
 : multivector< ex,2>(m) {}
std::Matrix::Matrix (const char * m[3][3]) inline
constructs a symbolic matrix with the symbols names given by the argument
Definition at line 74 of file multivector.h.
                             : multivector< ex,2>(0,3,3){
         for(uint i=0;i<3;i++)
                 for(uint j=0;j<3;j++) at(i)[j]=symbol(m[i][j]);
         }
std::Matrix::Matrix (const char * name, const char ** index1, const char ** index2) inline
constructs a symbolic matrix with the symbols names given by the arguments
Definition at line 79 of file multivector.h.
                                                                     : multivector< ex,2>(0,3,3){
         for(uint i=0;i<3;i++)
                 for(uint j=0;j<3;j++){
                          string res=string(name)+"_{"+string(index1[i])+" "+string(index2[j])+"}";
                          //cout<<res<<endl;
                          at(i)[j]=symbol(res.c_str());
                          }
         }
std::Matrix::Matrix (ex m1, ex m2, ex m3) inline
constructs a diagonal matrix
Definition at line 88 of file multivector.h.
                            : multivector< ex,2>(0,3,3) {
         at(0)[0]=m1;
         at(1)[1]=m2;
         at(2)[2]=m3;
 }
std::Matrix::Matrix (ex m1) inline
constructs a diagonal matrix with all diagonal elements equal
Definition at line 95 of file multivector.h.
              : multivector< ex,2>(0,3,3){
         Matrix();
         at(0)[0]=m1;
         at(1)[1]=m1;
         at(2)[2]=m1;
         }
std::Matrix::Matrix (ex t12, ex t13, ex t23, ex d13) inline
constructs a unitary matrix in the standard form
Definition at line 102 of file multivector.h.
                                       : multivector< ex,2>(0,3,3) {
         Matrix();
         ex c12=cos(t12), c13=cos(t13), c23=cos(t23);
         ex s12=sin(t12), s13=sin(t13), s23=sin(t23);
         ex e13=exp(I*d13);
         ex e13t=ex(1)/e13;
         ex aux[3][3]={
                         {c12*c13,s12*c13,s13*e13t},
                         {-s12*c23-c12*s23*s13*e13,c12*c23-s12*s23*s13*e13,s23*c13},
                         {s12*s23-c12*c23*s13*e13,-c12*s23-s12*c23*s13*e13,c13*c23}
                         };
         for(uint i=0;i<3; i++) at(i).assign(aux[i],aux[i]+3);
         }
Member Function Documentation
Matrix std::Matrix::conjugate () const inline
computes the hermitian conjugate of the matrix
Definition at line 125 of file multivector.h.
References conjugate().
Referenced by BGLmodels::BGL::BGL(), conjugate(), and BGLmodels::Mixes::Mixes().
{
         Matrix res;
         for(uint i=0;i<3;i++)
                 for(uint j=0;j<3;j++)
                         res[i][j]=at(j)[i].conjugate();
         return res;
 }
ex std::Matrix::cs (ex t12) inline
used in the unitary constructor
Definition at line 117 of file multivector.h.
              {
         return (exp(I*t12)+1/exp(I*t12))/2;
         }
ex std::Matrix::sn (ex t12) inline
used in the unitary constructor
Definition at line 121 of file multivector.h.
              {
         return -I*(exp(I*t12)-1/exp(I*t12))/2;
         }
The documentation for this class was generated from the following file:
multivector.h