flavour: Peak Class Reference
Peak Class Reference
A class containing the parameters of a maximum of the likelihood function.
#include <MCMC.h>
Public Member Functions
Peak (const Model *m, int maxx=0)
void findPeak ()
bool adjuststeps ()
Public Attributes
const Model * model
parameters pr
double lmax
double llmax
double area
double larea
bool max
Detailed Description
A class containing the parameters of a maximum of the likelihood function.
Definition at line 11 of file MCMC.h.
Constructor & Destructor Documentation
Peak::Peak (const Model * m, int maxx = 0) inline
Definition at line 13 of file MCMC.h.
                                         : model(m), pr(m->generateparameters(maxx)), max(maxx){
                 lmax=model->likelihood(pr);
                 }
Member Function Documentation
bool Peak::adjuststeps () inline
Definition at line 136 of file MCMC.h.
References parameters::area().
{
                  parameters p1(pr);
                  for(uint i=0;i<pr.size(); i++){
                            double s=p1[i].step;
                            p1[i].value+=s;
                            double x=(lmax-model->likelihood(p1))*2/lmax/s/s;
                            double x0=std::pow(2/(pr[i].max-pr[i].min),2);
                            if(x<x0) return 0;
                           // cout<<"X "<<x<<endl;
                            pr[i].step=1/sqrt(x);
                            p1[i].value-=s;
                            }
            area=pr.area();
            larea=area*lmax;
            return 1;
         }
void Peak::findPeak () inline
Definition at line 17 of file MCMC.h.
References parameters::next().
Referenced by Proposal::findPeaks().
{
            llmax=model->loglike(pr,1,max);
            area=1;
           uint fixed=1e2;
           uint f=fixed;
           double d=1;
           //cout<<"f "<<f<<"llmax "<<llmax<<endl;
                 for(uint i=1e5;i;i--){
                         parameters p1(pr);
                         p1.next(model->r,d);
                         double l1=llmax;
                         if(!model->veto(p1,max)){l1=model->loglike(p1,1,max);
                                 }
                         if(l1>llmax){pr=p1;  llmax=l1; f=fixed;}
                         else {f--; if(!f) {d/=100; f=fixed; if(d<1e-2) break;}}
                     }
            cout<<"d "<<d<<"llmax "<<llmax<<endl;
            if(llmax<-1000) lmax=0;
            else{lmax=exp(llmax);
                 area=pr.area();
             larea=area*lmax;
             }
         }
Member Data Documentation
double Peak::area
Definition at line 156 of file MCMC.h.
double Peak::larea
Definition at line 157 of file MCMC.h.
double Peak::llmax
Definition at line 155 of file MCMC.h.
Referenced by Proposal::findPeaks().
double Peak::lmax
Definition at line 155 of file MCMC.h.
Referenced by Proposal::findPeaks(), and main().
bool Peak::max
Definition at line 158 of file MCMC.h.
const Model* Peak::model
Definition at line 153 of file MCMC.h.
parameters Peak::pr
Definition at line 154 of file MCMC.h.
Referenced by Proposal::findPeaks(), and main().
The documentation for this class was generated from the following file:
MCMC.h