flavour: BGLmodels::calcubtosgamma2 Class Reference
BGLmodels::calcubtosgamma2 Class Reference
calculus of the constraints coming from the b->s gamma decay
#include <Formulas.h>
Public Member Functions
calcubtosgamma2 (const Mixes &mixes)
double operator() (const parameters &p) const
double width (const parameters &p, int option=0) const
double A0 (double x) const
double A1 (double x) const
double A2 (double x) const
double A3 (double x) const
Public Attributes
ROOT::Math::Interpolator inter1
ROOT::Math::Interpolator inter2
ROOT::Math::Interpolator inter3
ROOT::Math::Interpolator inter4
ROOT::Math::Interpolator Mu_ [3]
ROOT::Math::Interpolator Md_ [3]
const uint ii
FUNCP_CUBA fp
const gauss2obs g1
const gauss2obs g2
double ratio
Static Public Attributes
static constexpr double calN =2.567e-3
static constexpr double a =7.8221
static constexpr double aee =0.4384
static constexpr double aer =-1.6981
static constexpr double a77 =0.8161
static constexpr double a7r =4.8802
static constexpr double a7er =-0.7827
static constexpr double a88 =0.0197
static constexpr double a8r =0.5680
static constexpr double a8er =-0.0601
static constexpr double a87r =0.1923
static constexpr double a7i =0.3546
static constexpr double a8i =-0.0987
static constexpr double aei =2.4997
static constexpr double a87i =-0.0487
static constexpr double a7ei =-0.9067
static constexpr double a8ei =-0.0661
Detailed Description
calculus of the constraints coming from the b->s gamma decay
Definition at line 279 of file Formulas.h.
Constructor & Destructor Documentation
BGLmodels::calcubtosgamma2::calcubtosgamma2 (const Mixes & mixes) inline
Definition at line 286 of file Formulas.h.
References BGLmodels::C7SM_Mt, BGLmodels::C8SM_Mt, BGLmodels::iDown, BGLmodels::iUp, BGLmodels::Mixes::N_, BGLmodels::Mixes::replacements, BGLmodels::Mixes::tanb, BGLmodels::tQuark, BGLmodels::Mixes::VN_, and BGLmodels::Vud().
                                            :
           ii(2),
           g1(3.43e-4,sqrt(2)*0.23e-4),
           g2(9.2e-6,4e-6),
           ratio(0){
                 //cout<<"C7 "<<C7SM_Mt<<" "<<C7SM_MW<<" "<<C7SM(std::pow(261.8/M_MW,2))<<endl;
                 double res[2];
            constexpr double C7SM_[2]={C7SM_Mt,C7SM_Mt};
            constexpr double C8SM_[2]={C8SM_Mt,C8SM_Mt};
            for(uint j=0; j<2; j++){
                 const uint i=2;
                 const CD epsilon=conj(Vud[0][j])*Vud[0][i]/conj(Vud[2][j])/Vud[2][i];
                 const double upsilon=norm(conj(Vud[2][j])*Vud[2][i]/Vud[1][i]);
                 const CD R7=(C7SM_Mt)/C7SM_MW;
                 const CD R8=(C8SM_Mt)/C8SM_MW;
                 const CD R7_=0;
                 const CD R8_=0;
                 res[j]=a+aee*norm(epsilon)+aer*epsilon.real()+aei*epsilon.imag();
                 res[j]+=a77*(norm(R7)+norm(R7_))+a7r*R7.real()+a7i*R7.imag();
                 res[j]+=a88*(norm(R8)+norm(R8_))+a8r*R8.real()+a8i*R8.imag();
                 res[j]+=a87r*(R8*conj(R7)+R8_*conj(R7_)).real()+a7er*(R7*conj(epsilon)).real()+a8er*(R8*conj(epsilon)).real();
                 res[j]+=a87i*(R8*conj(R7)+R8_*conj(R7_)).imag()+a7ei*(R7*conj(epsilon)).imag()+a8er*(R8*conj(epsilon)).imag();
                 res[j]*=calN/100*upsilon;
         }
         //cout<<"Btosgamma "<<res[0]/9.2e-6<<" "<<res[1]/3.15e-4<<endl;
                 ifstream finter("interpolation.dat");
     if(!finter.is_open()){
                 cout<<"ERROR: interpolation.dat not found"<<endl;
                 exit(1);
                 }
     vector<double> vinter0, vinter1, vinter2;
     while(!finter.eof()){
                 double a=0,b=0,c=0;
                 finter>>a>>b>>c;
                 if(a!=0){
                 // cout<<a<<" "<<b<<" "<<c<<endl;
                  vinter0.push_back(a);
                  vinter1.push_back(b);
                  vinter2.push_back(c);
             }
                 }
         inter1.SetData(vinter0,vinter1);
         inter2.SetData(vinter0,vinter2);
         finter.close();
             ifstream finter2("masses.dat");
     if(!finter2.is_open()){
                 cout<<"ERROR: masses.dat not found"<<endl;
                 exit(1);
                 }
     vector<vector<double> > m_(7);
     while(!finter2.eof()){
                 for(uint i=0; i<7;i++) {
                         double a=0;
                         finter2>>a;
                         if(a!=0) {
                                 if(i==0) a=log(a);
                                 else if(i<4) a*=1e-3;
                                 m_[i].push_back(a);
                         //      cout<<a<<" ";
                         }
                 } //cout<<endl;
                 }
         for(uint i=0; i<3;i++) {
                 Md_[i].SetData(m_[0],m_[2*i+1]);
                 Mu_[i].SetData(m_[0],m_[2*i+2]);
         }
 //      cout<<"Eval "<<Mu_[2].Eval(log(100.0))<<endl;
 //      cout<<"Eval "<<Md_[2].Eval(log(100.0))<<endl;
         finter2.close();
     ifstream finter3("interpolation2.dat");
     if(!finter3.is_open()){
                 cout<<"ERROR: interpolation2.dat not found"<<endl;
                 exit(1);
                 }
     vector<double> vinter20, vinter21, vinter22;
     while(!finter3.eof()){
                 double a=0,b=0,c=0;
                 finter3>>a>>b>>c;
                 if(a!=0){
                 // cout<<a<<" "<<b<<" "<<c<<endl;
                  vinter20.push_back(a);
                  vinter21.push_back(b);
                  vinter22.push_back(c);
             }
                 }
         inter3.SetData(vinter20,vinter21);
         inter4.SetData(vinter20,vinter22);
         finter3.close();
         vector<ex> vex(24);
            const uint i=ii;
         for(uint j=0;j<2;j++)
         for(uint k=0;k<3;k++){
             vex[j*6+k*2+0]=mixes.VN_[tQuark][iUp][k][j].conjugate()*mixes.VN_[tQuark][iUp][k][i];
             vex[j*6+k*2+1]=mixes.N_[tQuark][iDown][j][k]*mixes.N_[tQuark][iDown][i][k].conjugate();
             vex[j+k*2+12]=-mixes.VN_[tQuark][iUp][k][j].conjugate()*mixes.VN_[tQuark][iDown][k][i];
             vex[j+k*2+18]=mixes.VN_[tQuark][iDown][k][j].conjugate()*mixes.VN_[tQuark][iDown][k][i];
                 }
         lst l;
     for(uint k=0;k<vex.size();k++){
                 vex[k]=vex[k].subs(mixes.replacements).evalf();
                 l.append(vex[k].real_part());
                 l.append(vex[k].imag_part());
                 }
         compile_ex(l, lst(mixes.tanb), fp);
         }
Member Function Documentation
double BGLmodels::calcubtosgamma2::A0 (double x) const inline
Definition at line 640 of file Formulas.h.
{
         return x*(2+3*x-6*x*x+ x*x*x+6*x*std::log(x))/(24*std::pow(1-x,4));
         }
double BGLmodels::calcubtosgamma2::A1 (double x) const inline
Definition at line 644 of file Formulas.h.
{
         return x*(-3+4*x-x*x-2*std::log(x))/(4*std::pow(1-x,3));
         }
double BGLmodels::calcubtosgamma2::A2 (double x) const inline
Definition at line 648 of file Formulas.h.
{
         return x/(6*std::pow(1-x,3))*((-7+5*x+8*x*x)/6.0+x*std::log(x)/(1-x)*(-2+3*x));
         }
double BGLmodels::calcubtosgamma2::A3 (double x) const inline
Definition at line 652 of file Formulas.h.
{
         return (-3+8*x-5*x*x+(6*x-4)*std::log(x))*x/(6*std::pow(1-x,3));
         }
double BGLmodels::calcubtosgamma2::operator() (const parameters & p) const inline virtual
Parameters
hipothesis the theoretical hypothesis
Returns
the logarithm of the probability of measuring what was measured, assuming that the hypothesis is true
Implements calcu.
Definition at line 406 of file Formulas.h.
References BGLmodels::C7SM_Mt, BGLmodels::C8SM_Mt, BGLmodels::mt_mt, and BGLmodels::Vud().
{
          double tanb=p[0].value;
          double y=p[1].value;
            double z=p[2].value;
            double w=p[3].value;
         double McH=y, MR=z, MI=w;
         double y0=y;
         if(y<mt_mt) y0=mt_mt;
          double QCD1[2]={inter3.Eval(y0),inter1.Eval(y)};
          double QCD2[2]={inter4.Eval(y0),inter2.Eval(y)};
          double Mu[3],Md[3];
         for(uint i=0;i<3;i++){
                 Mu[i]=Mu_[i].Eval(log(y));
                 Md[i]=Md_[i].Eval(log(z));
         }
            const uint i=ii;
            CD CC7[2],DD7[2],CC8[2],DD8[2];
            double res[2];
           // constexpr double C7SM_[2]={C7SM_Mt,C7SM_Mb};
           // constexpr double C8SM_[2]={C8SM_Mt,C8SM_Mb};
            std::array<double,48> ret;
            const int n=1,m=48;
            fp(&n,&(tanb),&m,&(ret[0]));
            for(uint j=0;j<2;j++){
                 const double mbottom=Md[i];
                 const double mstrange=Md[j];
                         //ex mbottom=mixes.M[tQuark][iDown][i][i];
                         //ex mstrange=mixes.M[tQuark][iDown][j][j];
                         CD C7,D7,C8,D8;
                         for(uint k=0;k<3;k++){
                         double mup=Mu[k];
                         double mdown=Md[k];
                         //ex mup=mixes.M[tQuark][iUp][k][k];
                         //ex mdown=mixes.M[tQuark][iDown][k][k];
                         //f1+=
                         double mmu=std::pow(mup/McH,2);
                         double mmdR=std::pow(mdown/MR,2);
                         double mmdI=std::pow(mdown/MI,2);
                         double A0u=A0(mmu);
                         double A1u=A1(mmu);
                         double A2u=A2(mmu);
                         double A3u=A3(mmu);
             double A0d=(A0(mmdR)+A0(mmdI));
                         double A1d=(A1(mmdR)-A1(mmdI));
                         CD f1(ret[j*12+4*k+0],ret[j*12+4*k+1]);
                         C7+=f1*A2u;
                         C8+=-2.0*f1*A0u;
                         CD f2=CD(ret[36+j*2+4*k+0],ret[36+j*2+4*k+1])*mstrange*mbottom/mup/mup;
                         //CD f2=f1*mstrange*mbottom/mup/mup;
                         D7+=f2*A2u;
                         D8+=-2.0*f2*A0u;
                         CD f12(ret[24+j*2+4*k+0],ret[24+j*2+4*k+1]);
                         C7+=f12*A3u;
                         C8+=2.0*f12*A1u;
                         CD f4(ret[j*12+4*k+2],ret[j*12+4*k+3]);
                         C7+=f4*A0d/3.0;
                         C8+=-f4*A0d;
                         C7+=f4*A1d/3.0;
                         C8+=-f4*A1d;
                         CD f6=f4*mstrange*mbottom/mdown/mdown;
                         D7+=f6*A0d/3.0;
                         D8+=-f6*A0d;
                         }
                 uint j0=j;
                 CC7[j]=(QCD1[j]*C7+QCD2[j]*C8)/2.0/conj(Vud[2][j])/Vud[2][i];
                 DD7[j]=(QCD1[j]*D7+QCD2[j]*D8)/2.0/conj(Vud[2][j])/Vud[2][i];
                 const double QCD3=(3*QCD2[j]/8+QCD1[j]);
                 CC8[j]=QCD3*C8/2.0/conj(Vud[2][j])/Vud[2][i];
                 DD8[j]=QCD3*D8/2.0/conj(Vud[2][j])/Vud[2][i];
                 const CD epsilon=conj(Vud[0][j])*Vud[0][i]/conj(Vud[2][j])/Vud[2][i];
                 const double upsilon=norm(conj(Vud[2][j])*Vud[2][i]/Vud[1][i]);
                 const CD R7=(C7SM_Mt+CC7[j])/C7SM_MW;
                 const CD R8=(C8SM_Mt+CD(0)*CC8[j])/C8SM_MW;
                 const CD R7_=(DD7[j])/C7SM_MW;
                 const CD R8_=CD(0)*(DD8[j])/C8SM_MW;
                 res[j]=a+aee*norm(epsilon)+aer*epsilon.real()+aei*epsilon.imag();
                 res[j]+=a77*(norm(R7)+norm(R7_))+a7r*R7.real()+a7i*R7.imag();
                 res[j]+=a88*(norm(R8)+norm(R8_))+a8r*R8.real()+a8i*R8.imag();
                 res[j]+=a87r*(R8*conj(R7)+R8_*conj(R7_)).real()+a7er*(R7*conj(epsilon)).real()+a8er*(R8*conj(epsilon)).real();
                 res[j]+=a87i*(R8*conj(R7)+R8_*conj(R7_)).imag()+a7ei*(R7*conj(epsilon)).imag()+a8er*(R8*conj(epsilon)).imag();
                 res[j]*=calN/100*upsilon;
                 /*res[j]=a+aee*norm(epsilon)+aer*epsilon.real()+aei*epsilon.imag();
                 res[j]+=a77*(norm(R7)+norm(R7_))+a7r*1+a7i*0;
                 res[j]+=a88*(norm(R8)+norm(R8_))+a8r*R8.real()+a8i*R8.imag();
                 res[j]+=a87r*1+a7er*(conj(epsilon)).real()+a8er*(R8*conj(epsilon)).real();
                 res[j]+=a87i*0+a7ei*(conj(epsilon)).imag()+a8er*(R8*conj(epsilon)).imag();
                 res[j]*=calN/100*upsilon;
                 */
         }
         double r1=3.15e-4+0.00247*(norm(CC7[1])+norm(DD7[1])-0.706*CC7[1].real());
         //ratio=res[0]/9.2e-6;
         //cout<<"RATIO "<<ratio<<endl;
         return g1.loglikelihood(r1)+0*g2.loglikelihood(res[0]);
            }
double BGLmodels::calcubtosgamma2::width (const parameters & p, int option = 0) const inline
Definition at line 517 of file Formulas.h.
References BGLmodels::C7SM_Mt, BGLmodels::C8SM_Mt, BGLmodels::mt_mt, and BGLmodels::Vud().
Referenced by BGL2::bsgammawidth(), and BGLmodels::BGL::bsgammawidth().
{
          double tanb=p[0].value;
          double y=p[1].value;
            double z=p[2].value;
            double w=p[3].value;
         double McH=y, MR=z, MI=w;
         double y0=y;
         if(y<mt_mt) y0=mt_mt;
          double QCD1[2]={inter3.Eval(y0),inter1.Eval(y)};
          double QCD2[2]={inter4.Eval(y0),inter2.Eval(y)};
          double Mu[3],Md[3];
         for(uint i=0;i<3;i++){
                 Mu[i]=Mu_[i].Eval(log(y));
                 Md[i]=Md_[i].Eval(log(z));
         }
            const uint i=ii;
            CD CC7[2],DD7[2],CC8[2],DD8[2];
            double res[2];
           // constexpr double C7SM_[2]={C7SM_Mt,C7SM_Mb};
           // constexpr double C8SM_[2]={C8SM_Mt,C8SM_Mb};
            std::array<double,24> ret;
            const int n=1,m=24;
            fp(&n,&(tanb),&m,&(ret[0]));
            for(uint j=0;j<2;j++){
                 const double mbottom=Md[i];
                 const double mstrange=Md[j];
                         //ex mbottom=mixes.M[tQuark][iDown][i][i];
                         //ex mstrange=mixes.M[tQuark][iDown][j][j];
                         CD C7,D7,C8,D8;
                         for(uint k=0;k<3;k++){
                         double mup=Mu[k];
                         double mdown=Md[k];
                         //ex mup=mixes.M[tQuark][iUp][k][k];
                         //ex mdown=mixes.M[tQuark][iDown][k][k];
                         //f1+=
                         double mmu=std::pow(mup/McH,2);
                         double mmdR=std::pow(mdown/MR,2);
                         double mmdI=std::pow(mdown/MI,2);
                         double A0u=0,A1u=0, A2u=0, A3u=0, A0d=0, A1d=0;
                         if(option==0 || option==1){
                         A0u=A0(mmu);
                         A1u=A1(mmu);
                         A2u=A2(mmu);
                         A3u=A3(mmu);
                         }
             if(option==0 || option==2){
             A0d=(A0(mmdR)+A0(mmdI));
                         A1d=(A1(mmdR)-A1(mmdI));
                         }
                         if(option==3){
             A0d=(A0(mmdR));
                         A1d=(A1(mmdR));
                         }
                         if(option==4){
             A0d=(A0(mmdI));
                         A1d=(-A1(mmdI));
                         }
                         CD f1(ret[j*12+4*k+0],ret[j*12+4*k+1]);
                         C7+=f1*A2u;
                         C8+=-2.0*f1*A0u;
                         CD f2=f1*mstrange*mbottom/mup/mup;
                         D7+=f2*A2u;
                         D8+=-2.0*f2*A0u;
                         C7+=-f1*A3u;
                         C8+=-2.0*f1*A1u;
                         CD f4(ret[j*12+4*k+2],ret[j*12+4*k+3]);
                         C7+=f4*A0d/3.0;
                         C8+=-f4*A0d;
                         C7+=f4*A1d/3.0;
                         C8+=-f4*A1d;
                         CD f6=f4*mstrange*mbottom/mdown/mdown;
                         D7+=f6*A0d/3.0;
                         D8+=-f6*A0d;
                         }
                 uint j0=j;
                 CC7[j]=(QCD1[j]*C7+QCD2[j]*C8)/2.0/conj(Vud[2][j])/Vud[2][i];
                 DD7[j]=(QCD1[j]*D7+QCD2[j]*D8)/2.0/conj(Vud[2][j])/Vud[2][i];
                 const double QCD3=(3*QCD2[j]/8+QCD1[j]);
                 CC8[j]=QCD3*C8/2.0/conj(Vud[2][j])/Vud[2][i];
                 DD8[j]=QCD3*D8/2.0/conj(Vud[2][j])/Vud[2][i];
                 const CD epsilon=conj(Vud[0][j])*Vud[0][i]/conj(Vud[2][j])/Vud[2][i];
                 const double upsilon=norm(conj(Vud[2][j])*Vud[2][i]/Vud[1][i]);
                 const CD R7=(C7SM_Mt+CC7[j])/C7SM_MW;
                 const CD R8=(C8SM_Mt+CD(0)*CC8[j])/C8SM_MW;
                 const CD R7_=(DD7[j])/C7SM_MW;
                 const CD R8_=CD(0)*(DD8[j])/C8SM_MW;
                 res[j]=a+aee*norm(epsilon)+aer*epsilon.real()+aei*epsilon.imag();
                 res[j]+=a77*(norm(R7)+norm(R7_))+a7r*R7.real()+a7i*R7.imag();
                 res[j]+=a88*(norm(R8)+norm(R8_))+a8r*R8.real()+a8i*R8.imag();
                 res[j]+=a87r*(R8*conj(R7)+R8_*conj(R7_)).real()+a7er*(R7*conj(epsilon)).real()+a8er*(R8*conj(epsilon)).real();
                 res[j]+=a87i*(R8*conj(R7)+R8_*conj(R7_)).imag()+a7ei*(R7*conj(epsilon)).imag()+a8er*(R8*conj(epsilon)).imag();
                 res[j]*=calN/100*upsilon;
                 /*res[j]=a+aee*norm(epsilon)+aer*epsilon.real()+aei*epsilon.imag();
                 res[j]+=a77*(norm(R7)+norm(R7_))+a7r*1+a7i*0;
                 res[j]+=a88*(norm(R8)+norm(R8_))+a8r*R8.real()+a8i*R8.imag();
                 res[j]+=a87r*1+a7er*(conj(epsilon)).real()+a8er*(R8*conj(epsilon)).real();
                 res[j]+=a87i*0+a7ei*(conj(epsilon)).imag()+a8er*(R8*conj(epsilon)).imag();
                 res[j]*=calN/100*upsilon;
                 */
         }
         double r1=3.15e-4+0.00247*(norm(CC7[1])+norm(DD7[1])-0.706*CC7[1].real());
         //ratio=res[0]/9.2e-6;
         //cout<<"RATIO "<<ratio<<endl;
         return g1.error(r1);
            }
Member Data Documentation
constexpr double BGLmodels::calcubtosgamma2::a =7.8221 static
Definition at line 283 of file Formulas.h.
constexpr double BGLmodels::calcubtosgamma2::a77 =0.8161 static
Definition at line 283 of file Formulas.h.
constexpr double BGLmodels::calcubtosgamma2::a7ei =-0.9067 static
Definition at line 284 of file Formulas.h.
constexpr double BGLmodels::calcubtosgamma2::a7er =-0.7827 static
Definition at line 283 of file Formulas.h.
constexpr double BGLmodels::calcubtosgamma2::a7i =0.3546 static
Definition at line 284 of file Formulas.h.
constexpr double BGLmodels::calcubtosgamma2::a7r =4.8802 static
Definition at line 283 of file Formulas.h.
constexpr double BGLmodels::calcubtosgamma2::a87i =-0.0487 static
Definition at line 284 of file Formulas.h.
constexpr double BGLmodels::calcubtosgamma2::a87r =0.1923 static
Definition at line 284 of file Formulas.h.
constexpr double BGLmodels::calcubtosgamma2::a88 =0.0197 static
Definition at line 283 of file Formulas.h.
constexpr double BGLmodels::calcubtosgamma2::a8ei =-0.0661 static
Definition at line 284 of file Formulas.h.
constexpr double BGLmodels::calcubtosgamma2::a8er =-0.0601 static
Definition at line 284 of file Formulas.h.
constexpr double BGLmodels::calcubtosgamma2::a8i =-0.0987 static
Definition at line 284 of file Formulas.h.
constexpr double BGLmodels::calcubtosgamma2::a8r =0.5680 static
Definition at line 283 of file Formulas.h.
constexpr double BGLmodels::calcubtosgamma2::aee =0.4384 static
Definition at line 283 of file Formulas.h.
constexpr double BGLmodels::calcubtosgamma2::aei =2.4997 static
Definition at line 284 of file Formulas.h.
constexpr double BGLmodels::calcubtosgamma2::aer =-1.6981 static
Definition at line 283 of file Formulas.h.
constexpr double BGLmodels::calcubtosgamma2::calN =2.567e-3 static
Definition at line 282 of file Formulas.h.
FUNCP_CUBA BGLmodels::calcubtosgamma2::fp
Definition at line 660 of file Formulas.h.
const gauss2obs BGLmodels::calcubtosgamma2::g1
Definition at line 661 of file Formulas.h.
const gauss2obs BGLmodels::calcubtosgamma2::g2
Definition at line 661 of file Formulas.h.
const uint BGLmodels::calcubtosgamma2::ii
Definition at line 659 of file Formulas.h.
ROOT::Math::Interpolator BGLmodels::calcubtosgamma2::inter1
Definition at line 656 of file Formulas.h.
ROOT::Math::Interpolator BGLmodels::calcubtosgamma2::inter2
Definition at line 656 of file Formulas.h.
ROOT::Math::Interpolator BGLmodels::calcubtosgamma2::inter3
Definition at line 656 of file Formulas.h.
ROOT::Math::Interpolator BGLmodels::calcubtosgamma2::inter4
Definition at line 656 of file Formulas.h.
ROOT::Math::Interpolator BGLmodels::calcubtosgamma2::Md_[3]
Definition at line 657 of file Formulas.h.
ROOT::Math::Interpolator BGLmodels::calcubtosgamma2::Mu_[3]
Definition at line 657 of file Formulas.h.
double BGLmodels::calcubtosgamma2::ratio mutable
Definition at line 662 of file Formulas.h.
The documentation for this class was generated from the following file:
Formulas.h