flavour: BGLmodels::Boson Class Reference
BGLmodels::Boson Class Reference
Gauge boson.
#include <BGL.h>
Public Member Functions
Boson ()
ex couplingL (const Fermion &f2, const Fermion &f1) const
ex couplingR (const Fermion &f2, const Fermion &f1) const
ex couplingdaggerL (const Fermion &f2, const Fermion &f1) const
ex couplingdaggerR (const Fermion &f2, const Fermion &f1) const
ex coupling (const Fermion &f2, const Fermion &f1, ex mu)
void reset ()
Public Attributes
BSpin s
ex mass
multivector< Matrix, 4 > C
Detailed Description
Gauge boson.
Definition at line 21 of file BGL.h.
Constructor & Destructor Documentation
BGLmodels::Boson::Boson () inline
Definition at line 24 of file BGL.h.
 : C(Matrix(),2,2,2,2){}
Member Function Documentation
ex BGLmodels::Boson::coupling (const Fermion & f2, const Fermion & f1, ex mu) inline
Definition at line 59 of file BGL.h.
References couplingL(), couplingR(), s, and BGLmodels::sScalar.
{
                 if(s==sScalar) return couplingL(f2,f1)*dirac_gammaL()+couplingR(f2,f1)*dirac_gammaR();
                 else return couplingL(f2,f1)*dirac_gammaL()+couplingR(f2,f1)*dirac_gammaR();
                 }
ex BGLmodels::Boson::couplingdaggerL (const Fermion & f2, const Fermion & f1) const inline
Definition at line 51 of file BGL.h.
References couplingL(), couplingR(), s, and BGLmodels::sScalar.
Referenced by BGLmodels::BGL::BGL(), and BGLmodels::BGL::CHdecaycoupling().
{
                 if(s==sScalar) return couplingR(f1,f2).conjugate();
                 return couplingL(f1,f2).conjugate();
                 }
ex BGLmodels::Boson::couplingdaggerR (const Fermion & f2, const Fermion & f1) const inline
Definition at line 55 of file BGL.h.
References couplingL(), couplingR(), s, and BGLmodels::sScalar.
Referenced by BGLmodels::BGL::CHdecaycoupling().
{
                 if(s==sScalar) return couplingL(f1,f2).conjugate();
                 return couplingR(f1,f2).conjugate();
                 }
ex BGLmodels::Boson::couplingL (const Fermion & f2, const Fermion & f1) const inline
Definition at line 26 of file BGL.h.
References C, BGLmodels::Fermion::flavour, BGLmodels::Fermion::helicity, BGLmodels::hLeft, BGLmodels::hRight, BGLmodels::Fermion::isospin, s, BGLmodels::sScalar, BGLmodels::sVector, and BGLmodels::Fermion::type.
Referenced by BGLmodels::BGL::BGL(), coupling(), couplingdaggerL(), couplingdaggerR(), BGLmodels::BGL::fermiontomeson(), and BGLmodels::BGL::mesondw().
{
                 bool quiralfilter=0;
                 if(f1.type!=f2.type) return 0;
                 if(s==sScalar){
                         if(f1.helicity!=hRight && f2.helicity!=hLeft) quiralfilter=1;
                         }
                 else if(s==sVector){
                         if(f1.helicity!=hRight && f2.helicity!=hRight) quiralfilter=1;
                         }
                 if(quiralfilter) return C[f2.type][f2.isospin][f1.isospin][hLeft][f2.flavour][f1.flavour];
                 return 0;
                 }
ex BGLmodels::Boson::couplingR (const Fermion & f2, const Fermion & f1) const inline
Definition at line 39 of file BGL.h.
References C, BGLmodels::Fermion::flavour, BGLmodels::Fermion::helicity, BGLmodels::hLeft, BGLmodels::hRight, BGLmodels::Fermion::isospin, s, BGLmodels::sScalar, BGLmodels::sVector, and BGLmodels::Fermion::type.
Referenced by BGLmodels::BGL::BGL(), coupling(), couplingdaggerL(), couplingdaggerR(), BGLmodels::BGL::fermiontomeson(), and BGLmodels::BGL::mesondw().
{
                 bool quiralfilter=0;
                 if(f1.type!=f2.type) return 0;
                 if(s==sScalar){
                         if(f2.helicity!=hRight && f1.helicity!=hLeft) quiralfilter=1;
                         }
                 else if(s==sVector){
                         if(f1.helicity!=hLeft && f2.helicity!=hLeft) quiralfilter=1;
                         }
                 if(quiralfilter) return C[f2.type][f2.isospin][f1.isospin][hRight][f2.flavour][f1.flavour];
                 return 0;
                 }
void BGLmodels::Boson::reset () inline
Definition at line 63 of file BGL.h.
References C.
Referenced by BGLmodels::BGL::BGL(), and BGL2::BGL2().
                     {
                 C=multivector<Matrix,4>(Matrix(),2,2,2,2);
                 }
Member Data Documentation
multivector<Matrix,4> BGLmodels::Boson::C
Definition at line 68 of file BGL.h.
Referenced by BGLmodels::BGL::BGL(), BGL2::BGL2(), couplingL(), couplingR(), and reset().
ex BGLmodels::Boson::mass
Definition at line 67 of file BGL.h.
Referenced by BGLmodels::BGL::BGL(), BGL2::BGL2(), BGLmodels::BGL::decaywidth(), BGLmodels::BGL::fermiontomeson(), BGLmodels::BGL::gRR2(), BGLmodels::BGL::mesondw(), BGLmodels::BGL::mesonmixing(), and BGLmodels::BGL::tautomu_tautoe().
BSpin BGLmodels::Boson::s
Definition at line 66 of file BGL.h.
Referenced by BGLmodels::BGL::BGL(), BGL2::BGL2(), coupling(), couplingdaggerL(), couplingdaggerR(), couplingL(), couplingR(), BGLmodels::BGL::decaywidth(), BGLmodels::BGL::fermiontomeson(), BGLmodels::BGL::get_integral_symb(), BGLmodels::BGL::gRR2(), BGLmodels::BGL::mesondw(), BGLmodels::BGL::mesonmixing(), and BGLmodels::BGL::tautomu_tautoe().
The documentation for this class was generated from the following file:
BGL.h