flavour: Proposal Class Reference
Proposal Class Reference
A class containing the parameters of a proposal for the next step in the Markov Chain.
#include <MCMC.h>
Public Member Functions
Proposal (const Model *m)
void findPeaks (uint ns=1, int max=0)
void getProposal ()
void getNextPoint ()
Public Attributes
const Model * model
vector< Peak > vPeak
Peak floatPeak
Peak proposal
double total
Detailed Description
A class containing the parameters of a proposal for the next step in the Markov Chain.
Definition at line 162 of file MCMC.h.
Constructor & Destructor Documentation
Proposal::Proposal (const Model * m) inline
Definition at line 165 of file MCMC.h.
 : model(m), floatPeak(m),proposal(m){}
Member Function Documentation
void Proposal::findPeaks (uint ns = 1, int max = 0) inline
Definition at line 167 of file MCMC.h.
References parameters::area(), Peak::findPeak(), Peak::llmax, Peak::lmax, and Peak::pr.
Referenced by main().
{
         //float pmin=-100, pmax=100, s=0.1;
     //floatPeak.s=s;
     //floatPeak.lmax=0;
     //int imax=-1;
     floatPeak=Peak(model,max);
     floatPeak.lmax=0;
     floatPeak.llmax=-1000;
    cout<<"started"<<endl;
         //for(uint i=5e1;i;i--){
         for(uint i=ns;i;i--){
                 Peak pp(model,max);
                 pp.findPeak();
                 if(pp.llmax>-15){
                 //for(uint j=0; j< pp.pr.size();j++){
                 //cout<<j<<" "<<pp.pr[j].value<<endl;
                 //}
                 //lst l=model->getlist(pp.pr);
                 //for(uint j=0; j< model->size();j++){
                 //      double mean=model->at(j).calculate(l);
                 //cout<<j<<" "<<mean<<" "<<sqrt(2*model->at(j).o->loglikelihood(mean))<<endl;
                 //}
                 }
                 if(pp.lmax>floatPeak.lmax){
                         cout<<i<<" "<<pp.lmax<<endl;
                         floatPeak.lmax=pp.lmax;
                         floatPeak.pr=pp.pr;
                         }
         }
         floatPeak.area=floatPeak.pr.area();
 }
void Proposal::getNextPoint () inline
Definition at line 210 of file MCMC.h.
Referenced by main().
                    {
         getProposal();
         double l1=0;
         l1=model->likelihood(proposal.pr);
         if(model->r->Rndm()<=l1/floatPeak.lmax){
                 floatPeak.lmax=l1;
                 floatPeak.pr.setvalues(proposal.pr);
         }
 }
void Proposal::getProposal () inline
Definition at line 200 of file MCMC.h.
                   {
         if(model->r->Rndm()<=0.9) {
                 proposal.pr=floatPeak.pr;
                 proposal.pr.next(model->r);
                 return;
                 }
         proposal.pr=model->generateparameters();
 }
Member Data Documentation
Peak Proposal::floatPeak
Definition at line 223 of file MCMC.h.
Referenced by main().
const Model* Proposal::model
Definition at line 220 of file MCMC.h.
Peak Proposal::proposal
Definition at line 223 of file MCMC.h.
double Proposal::total
Definition at line 224 of file MCMC.h.
vector<Peak> Proposal::vPeak
Definition at line 222 of file MCMC.h.
The documentation for this class was generated from the following file:
MCMC.h