flavour: BGLmodels Namespace Reference
BGLmodels Namespace Reference
Classes
class BGL
Implementation of the BGL model.
class Boson
Gauge boson.
class calcuBmumu
calculus of the constraints coming from the B->mu mu decay
class calcubtosgamma2
calculus of the constraints coming from the b->s gamma decay
class calcuOblique
calculus of the constraints coming from the oblique parameters
class Fermion
a fermion properties
class Matrixx
a class to represent the mixing matrices VCKM and VPMNS
class Meson
a meson properties
class Mixes
definition of the couplings for the different BGL models
Typedefs
typedef std::complex< double > CD
typedef std::array< CD, 3 > Vector3c
typedef std::array< std::array< CD, 3 >, 3 > Matrix3c
Enumerations
enum FType { tLepton, tQuark }
enum FIsospin { iUp, iDown }
enum FFlavour { fElectron, fMuon, fTau, fAny }
enum FCharge { cParticle, cAntiParticle }
enum FHelicity { hLeft, hRight, hAny }
enum BSpin { sScalar, sVector, sAny }
Functions
const Matrixx Vud (13.04 *M_PI/180, 0.201 *M_PI/180, 2.38 *M_PI/180, 1.2)
constexpr double C7SM (double x)
constexpr double C8SM (double x)
Variables
constexpr double M_GF =1.166371e-5
constexpr double M_MZ =91.1876
constexpr double M_MW =80.398
constexpr double M_cos2 =std::pow(M_MW/M_MZ,2)
constexpr double M_Mu [3] ={2.4e-3,1.29,172.9}
constexpr double M_Md [3] ={5.3e-3,95e-3,4.2}
constexpr double M_Ml [3] ={0.510998910e-3,105.6583715e-3,1776.82e-3}
const Matrixx Vnl =Matrixx(33.6*M_PI/180,9.11*M_PI/180,40.4*M_PI/180,M_PI/4).conjugate()
constexpr double mt_mt =163.3
constexpr double mt_mW =174.2
constexpr double mt_mb =261.8
constexpr double C7SM_MW =C7SM(std::pow(mt_mW/M_MW,2))
constexpr double C7SM_Mt =C7SM(std::pow(mt_mt/M_MW,2))
constexpr double C7SM_Mb =-0.353
constexpr double C8SM_MW =C8SM(std::pow(mt_mW/M_MW,2))
constexpr double C8SM_Mt =C8SM(std::pow(mt_mt/M_MW,2))
constexpr double C8SM_Mb =C8SM(std::pow(mt_mb/M_MW,2))
Typedef Documentation
typedef std::complex<double> BGLmodels::CD
Definition at line 65 of file Formulas.h.
typedef std::array<std::array<CD,3>,3> BGLmodels::Matrix3c
Definition at line 67 of file Formulas.h.
typedef std::array<CD,3> BGLmodels::Vector3c
Definition at line 66 of file Formulas.h.
Enumeration Type Documentation
enum BGLmodels::BSpin
Enumerator
sScalar
sVector
sAny
Definition at line 27 of file Formulas.h.
 {sScalar, sVector,sAny};
enum BGLmodels::FCharge
Enumerator
cParticle
cAntiParticle
Definition at line 25 of file Formulas.h.
 {cParticle,cAntiParticle};
enum BGLmodels::FFlavour
Enumerator
fElectron
fMuon
fTau
fAny
Definition at line 24 of file Formulas.h.
 {fElectron,fMuon,fTau,fAny};
enum BGLmodels::FHelicity
Enumerator
hLeft
hRight
hAny
Definition at line 26 of file Formulas.h.
 {hLeft,hRight,hAny};
enum BGLmodels::FIsospin
Enumerator
iUp
iDown
Definition at line 23 of file Formulas.h.
 {iUp,iDown};
enum BGLmodels::FType
Enumerator
tLepton
tQuark
Definition at line 22 of file Formulas.h.
 {tLepton,tQuark};
Function Documentation
constexpr double BGLmodels::C7SM (double x)
Definition at line 264 of file Formulas.h.
{
         return ((1/(x-1)+3)*x*std::log(x)+(-8*x*x-5*x+7)/6)*x/4/std::pow(x-1,3);
         }
constexpr double BGLmodels::C8SM (double x)
Definition at line 268 of file Formulas.h.
{
         return (-3/(x-1)*x*std::log(x)+(-x*x+5*x+2)/2)*x/4/std::pow(x-1,3);
         }
const Matrixx BGLmodels::Vud (13.04 *M_PI/ 180, 0.201 *M_PI/ 180, 2.38 *M_PI/ 180, 1. 2)
Referenced by BGLmodels::calcuBmumu::calcuBmumu(), BGLmodels::calcubtosgamma2::calcubtosgamma2(), main(), BGLmodels::calcubtosgamma2::operator()(), and BGLmodels::calcubtosgamma2::width().
Variable Documentation
constexpr double BGLmodels::C7SM_Mb =-0.353
Definition at line 272 of file Formulas.h.
constexpr double BGLmodels::C7SM_Mt =C7SM(std::pow(mt_mt/M_MW,2))
Definition at line 272 of file Formulas.h.
Referenced by BGLmodels::calcubtosgamma2::calcubtosgamma2(), BGLmodels::calcubtosgamma2::operator()(), and BGLmodels::calcubtosgamma2::width().
constexpr double BGLmodels::C7SM_MW =C7SM(std::pow(mt_mW/M_MW,2))
Definition at line 272 of file Formulas.h.
constexpr double BGLmodels::C8SM_Mb =C8SM(std::pow(mt_mb/M_MW,2))
Definition at line 273 of file Formulas.h.
constexpr double BGLmodels::C8SM_Mt =C8SM(std::pow(mt_mt/M_MW,2))
Definition at line 273 of file Formulas.h.
Referenced by BGLmodels::calcubtosgamma2::calcubtosgamma2(), BGLmodels::calcubtosgamma2::operator()(), and BGLmodels::calcubtosgamma2::width().
constexpr double BGLmodels::C8SM_MW =C8SM(std::pow(mt_mW/M_MW,2))
Definition at line 273 of file Formulas.h.
constexpr double BGLmodels::M_cos2 =std::pow(M_MW/M_MZ,2)
Definition at line 60 of file Formulas.h.
constexpr double BGLmodels::M_GF =1.166371e-5
Definition at line 57 of file Formulas.h.
constexpr double BGLmodels::M_Md[3] ={5.3e-3,95e-3,4.2}
Definition at line 62 of file Formulas.h.
constexpr double BGLmodels::M_Ml[3] ={0.510998910e-3,105.6583715e-3,1776.82e-3}
Definition at line 63 of file Formulas.h.
constexpr double BGLmodels::M_Mu[3] ={2.4e-3,1.29,172.9}
Definition at line 61 of file Formulas.h.
constexpr double BGLmodels::M_MW =80.398
Definition at line 59 of file Formulas.h.
Referenced by BGLmodels::BGL::BGL(), and BGL2::BGL2().
constexpr double BGLmodels::M_MZ =91.1876
Definition at line 58 of file Formulas.h.
Referenced by BGLmodels::BGL::BGL(), and BGL2::BGL2().
constexpr double BGLmodels::mt_mb =261.8
Definition at line 262 of file Formulas.h.
constexpr double BGLmodels::mt_mt =163.3
Definition at line 262 of file Formulas.h.
Referenced by BGLmodels::calcubtosgamma2::operator()(), and BGLmodels::calcubtosgamma2::width().
constexpr double BGLmodels::mt_mW =174.2
Definition at line 262 of file Formulas.h.
const Matrixx BGLmodels::Vnl =Matrixx(33.6*M_PI/180,9.11*M_PI/180,40.4*M_PI/180,M_PI/4).conjugate()
Definition at line 98 of file Formulas.h.